### ISSUE TITLE
Launch problem

### ISSUE THREAD

**Issue by FenixEu** [mr-guard/dayz-server-manager#10]
Good afternoon.
The config and the exe file itself were copied to the folder with the server.
Renamed the config. Configured the config correctly.
When you run the exe file, it just opens for 1-2 seconds and closes.
The config is configured correctly, the antivirus is disabled, and it has been launched as administrator.
What could be the problem?

Been on windows 10 and 11.

Sorry for the translation.

**Comment by mr-guard** [comment]
Can you launch it from a console and send me the logs?

**Comment by FenixEu** [comment]
![image](https://user-images.githubusercontent.com/90526947/132988396-9f46e0e5-b1be-425f-8089-80515ec15f68.png)
there are no logs.
only that the console starts up for 1 second

**Comment by mr-guard** [comment]
I'll prepare a new version which logs to a file automatically.
This should make it easier.

Until then:
Can you open a powershell in the folder where the server-manager.exe is (on win10 this can usually be done by holding left shift and right click inside the folder, then there will be a 'open with powershell option')

When it is open just type dayz-server-manager.exe

This will open the server manager inside the powershell window, which will prevent it from closing the console and should (hopefully) show some output

(Sorry if you already did that, it just doesnt look like it from the screenshot and your discription)

**Comment by FenixEu** [comment]
![image](https://user-images.githubusercontent.com/90526947/133045877-3abae55e-d808-41fb-87b2-878090bdb42a.png)

dayz-server-manager.exe: The name "dayz-server-manager.exe" is not recognized as the name of a cmdlet, function, script, or
the program being executed. Check the spelling of the name, as well as the presence and correctness of the path, and then from the city
 try.
line: 1 character: 1
+ dayz-server-manager.exe
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo: ObjectNotFound: (dayz-server-manager.exe: String) [], CommandNotFoundException
    + FullyQualifiedErrorId: CommandNotFoundException


Suggestion [3, General]: The dayz-server-manager.exe command was not found, but exists at the current location. By default, Windows PowerShell does not load commands from the current location. If you are sure the command is reliable, enter ". \ Dayz-server-manager.exe". For more information, use the "get-help about_Command_Precedence" command.

**Comment by FenixEu** [comment]
![image](https://user-images.githubusercontent.com/90526947/133047014-91becc94-ff41-4aeb-85ac-ea0adb03d741.png)
![image](https://user-images.githubusercontent.com/90526947/133047097-cce966dd-f71f-490a-9f8f-d042375ed25d.png)

**Comment by FenixEu** [comment]
for a second, an empty window opens and hides
