### ISSUE TITLE
Unexpected Tokens

### ISSUE THREAD

**Issue by ClassifiedRebel** [mr-guard/dayz-server-manager#100]
As I go through the setup I just get unexpected tokens in JSON, as I changes things I get them on line 509, 538 and more pending what I change and if I go to that line there are no options.

**Comment by mr-guard** [comment]
Use a json linter
They will show you json syntax errors in your file.

I recommend using VSCode to edit the config manually

**Comment by mr-guard** [comment]
I will close this since no further updates were provided

**Comment by ClassifiedRebel** [comment]
The errors have gone away but it still never starts the server.
