### ISSUE TITLE
Server won't restart after it was locked.

### ISSUE THREAD

**Issue by Caaruzo** [mr-guard/dayz-server-manager#102]
Hi there.
I found an issue that drives me crazy.
I shutdown the server while restart is locked, so i can do some changes.
After finished i unlock the restart (it tells me successfully unlocked).
The Server never starts after this. In console it still tells me "Monitor      | Detected server restart lock state. Skipping server check".

What might the cause of that and how to fix?

Thx very much.

**Comment by mr-guard** [comment]
Will have a look into this

**Comment by itzeddie** [comment]
Can confirm the lock works as I would expect. However when pressing unlock the CLI output mentions checking for updates, but never actually logs out an unlock.

**Comment by mr-guard** [comment]
Will be fixed in the next version

**Comment by Caaruzo** [comment]
works. thx much
