### ISSUE TITLE
Compiling manually

### ISSUE THREAD

**Issue by Caaruzo** [mr-guard/dayz-server-manager#106]
Hello there. 
I try to do some translation changes, for myself.
In case of that, ill try to compile by myself. Iam running Visualstudio 2022, with installed Nodejs,pythong and c++ desktop.

Whenever i run choco install visualstudio2019buildtools -y, ill get an error.

Failures
 - visualstudio2019buildtools - Unable to resolve dependency 'kb2919355': Unable to find a version of 'kb2919355' that is compatible with 'dotnetfx 4.7.2 constraint: kb2919355 (>= 1.0.20160915)', 'KB2999226 1.0.20161023 constraint: kb2919355 (>= 1.0.20160915)', 'vcredist140 14.38.33135 constraint: kb2919355 (>= 1.0.20160915)', 'visualstudio2019buildtools 16.11.33 constraint: kb2919355 (>= 1.0.20160915)'.

The thing is, the kbb mentioned is for windows 8.1. Iam running on windows 11.

Someone can tell me what to do please to get it compiled locally? Thx very much.

**Comment by Caaruzo** [comment]
No chance for me to compile this. Also not with vs2019. installed all depencies, like build tools 2019 c++etc. Always complains about missing vc and such stuff. Environment is set. Is there any chance to get an updated compile guide please?

**Comment by mr-guard** [comment]
I cannot really provide much help as this really boils down to your setup
NodeGyp is used to build the native node modules required by the manager
The error says that node-gyp cannot find your Visual Studio installation and also hints:
`msvs_version not set from command line or npm config`

Google for the nodegyp setup setup and how to set these options
Adding VS to your PATH might be enough, but I am not sure


If everything else fails, you can just create a fork and the github pipeline will built it for you.
You can then download the exe as an artifact

**Comment by Caaruzo** [comment]
ok ty
