### ISSUE TITLE
events scheduling

### ISSUE THREAD

**Issue by Setman590** [mr-guard/dayz-server-manager#110]
Hi,

When doing server restarts, I noticed that in the DayZ console it is coming up with the restart notifications,
but not showing in game. Did I miss something?

**Comment by mr-guard** [comment]
Maybe you have got a Mod that hides the RCON messages ingame

**Comment by Setman590** [comment]
Looks like its when you run Expansion Mods, works without any mods

**Comment by mr-guard** [comment]
Ok, going to close this, as it is a mod issue
