### ISSUE TITLE
watcher mod have only config.bin

### ISSUE THREAD

**Issue by RomanBAH** [mr-guard/dayz-server-manager#12]
Hello, you make awesome tool. But i have a problem. I can't monitoring server on map, no one vehicle or players i can't see.
When server start, in path @DayZServerManager creating new mod Scripts.pbo every time. 
But inside this pbo i see only config.bin
When i try compile pbo from watcher_mod folder, and give it to server mod, i have error on start up, "Can't compile engine"
Can you check it?

Error log when i give pbo compiling by my self
`
Log D:\JNVanila\JNVanila\profiles\script_2021-10-11_04-10-39.log started at 11.10. 04:10:39

SCRIPT    (E): @"DayZServerManager/Scripts/Common,-1": Path not found
SCRIPT    (E): Can't compile "Engine" script module!

DayZServerManager/Scripts/Common: Path not found
`

**Comment by 2557530** [comment]
And IsMissionClient() can't work with full vanilla server, this must replace with !GetGame().IsClient()

https://github.com/mr-guard/dayz-server-manager/blob/601d75ef1f233c9f99cfc36b21b77b6c7461d459/watcher_mod/DayZServerManager/Scripts/5_Mission/DayZServerManager/Game/DayZServerManagerWatcher.c#L82

**Comment by 2557530** [comment]
Ok, i am trying to make PR))

Can you give example for hook on server start? 
I need run my own bat script every time before server start.

**Comment by mr-guard** [comment]
Sorry for breaking promises but I won't be able to look into it this weekend.

I will update this issue once I find some spare time

**Comment by mr-guard** [comment]
Thanks for the pull request.

I have been busy the last few months, but I have been able to put in some work into the manager lately.
There will be a rewrite of the manager (soon) which should fix your issues

Please stay patient, I will keep you informed :)

**Comment by 2557530** [comment]
Thank you, I am very glad to see your answer =) 
And now we have new problems) 
1. We cant add custom config key, like enableCfgGameplayFile = 1;
2. Map are broken, because cant resolve this addres https://senfo.space/dayzmaps/chernarusplus/data.json
And when map be working, they show wrong coordinates (just little lower then real position)
3. After few days of working, manager crashing without any logging. 

But anywau, manager are awesome, hope you can make some cool update for fix it 👍

**Comment by mr-guard** [comment]
The first two issues should be resolved in v2.1.3

This is a intermediate version while I work on 3.0.0

**Comment by 2557530** [comment]
Very glad to see you )) Thanks for new update. 
Can you teach me little bit? How you pack your project? 
I wanna try to fix some bugs and test it on my own server.

**Comment by mr-guard** [comment]
To compile the typescript to JavaScript

> npm run build

To compile and pack it into a exe

> npm run buildAndPack

Note: this requires you to have mikeros tools installed and available in the PATH

Have a look in the package.json
It contains all build scripts

**Comment by 2557530** [comment]
Many thanks, i will try it on weekend
