### ISSUE TITLE
Linux Server high cpu usage?

### ISSUE THREAD

**Issue by Villhahallon** [mr-guard/dayz-server-manager#120]
Hello,  Not sure if this is a problem or just how it is... The manager say that the server is using 100& of the cpu, and also when looking from the terminal. 

Is it possible to lower the cpu usage? 
Not running any mods on the server. 

Server is hosted on a proxmox vm, I don't have this problem on any of my other servers that are running windows.

![image](https://github.com/mr-guard/dayz-server-manager/assets/46343117/24807918-3f0d-4099-b931-67f8c8d3f280)
![image](https://github.com/mr-guard/dayz-server-manager/assets/46343117/edcbd1f5-f381-48c2-8d03-4b5ed7d8fb23)
![image](https://github.com/mr-guard/dayz-server-manager/assets/46343117/6529b3c2-b685-4ba4-98cb-2e9781bd6a65)
![image](https://github.com/mr-guard/dayz-server-manager/assets/46343117/1ca0c104-3610-4205-86b1-9ea60335ca5a)

**Comment by mr-guard** [comment]
On linux the DayZ server runs multiple processes and the manager only see the first one

Due to how the main game loop is implemented, that process always runs at 100%.

Scanning the child processes would solve the visual representation, but it would incur a lot of overhead

**Comment by Villhahallon** [comment]
Alright, Thanks for the information.
Going to migrate all my servers to linux this week then and see how that works out
