### ISSUE TITLE
WARNING: Server possibly got stuck!

### ISSUE THREAD

**Issue by GameAreaCZ** [mr-guard/dayz-server-manager#124]
I am getting spammed the discord channel with this, but the servers seems to be totally fine?

And it seems that is reporting the status too often?
![obrazek](https://github.com/mr-guard/dayz-server-manager/assets/82257025/c1131f79-40fa-4576-b73e-428bce105d70)

**Comment by mr-guard** [comment]
if the server is fine you can disable the warning in the config
this check only monitory the cpu usage of the server
If its the same for too long, it prints the message
if the server is idle with no players on it, it might report false positives

**Comment by GameAreaCZ** [comment]
Thank you.
