### ISSUE TITLE
Can't connect to the Interface when server running

### ISSUE THREAD

**Issue by mhyssasilva** [mr-guard/dayz-server-manager#131]
after a clean restart, I can't access to the web interface anymore 

infinite loading 

![image](https://github.com/mr-guard/dayz-server-manager/assets/142730259/8a5e53b5-a0be-4e2e-b9f0-a7690462a5a4)

dis someone knows this issue ? 

Thanks

**Comment by SGCFORCE** [comment]
Hello!

Have you forwarded port 2313 on your router?
You may also need to add it in the firewall and add a rule for incoming connections.

**Comment by mr-guard** [comment]
Make sure the server is running and you are using the correct ip/port if you have changed it in the config

**Comment by mhyssasilva** [comment]
No no it was working but sometimes not, i have a timeout

But it's never happened again so, we can close the issue ^^
