### ISSUE TITLE
Problems with rcon

### ISSUE THREAD

**Issue by IForcEI** [mr-guard/dayz-server-manager#133]
Hello! You have a wonderful application, I’m little by little figuring out how to use it. The server starts successfully and everything is fine, but I don’t understand why I can’t connect to rcon. It always uses different ports. As I understand it, because of this I cannot use the rcon web interface.

I am sorry for my English)

![Снимок экрана 2024-04-06 012434](https://github.com/mr-guard/dayz-server-manager/assets/15628553/93d31fc0-1bdb-4e6c-a330-115cebeb1b2b)

Because of this, I understand that I cannot use this menu.
![Снимок экрана 2024-04-06 012724](https://github.com/mr-guard/dayz-server-manager/assets/15628553/87de8351-d55e-4d7b-bcbb-92d375dd122f)

**Comment by mr-guard** [comment]
This message isnt "bad". It just logs what the RCON **Client** is doing.
It always has to use a port on your computer thats actually free. that why its usually always a different one

The RCON server in the DayZ Server always listens on the same port.

Usually the RCON connection takes some time to get established after the server has started (~1-2minutes). It will then log in the server console that it has connected successfully.
If thats not happening then there might be an issue with your config or your server setup

**Comment by SGCFORCE** [comment]
Oh, that's it! Thank you very much for the clarification! I'll try now!

**Comment by SGCFORCE** [comment]
No matter how strange it may sound, after I changed the password to a different one, everything worked! The only thing I added to the empty field is Rсon IP 127.0.0.1. It’s even kind of strange, because according to the standard it was exactly like that, but after adding it, it was still able to connect!
