### ISSUE TITLE
mapHost

### ISSUE THREAD

**Issue by SGCFORCE** [mr-guard/dayz-server-manager#139]
Hello! I have a problem with displaying the map. Can you tell me what this could be related to?
![image](https://github.com/mr-guard/dayz-server-manager/assets/15628553/f52c2ca4-e9e6-4777-955b-9413fdfb9e26)

**Comment by jonni111** [comment]
Hello, my card is not working either.

**Comment by SGCFORCE** [comment]
![image](https://github.com/mr-guard/dayz-server-manager/assets/15628553/43dea9c1-8952-4d00-b16a-0bd8a44e688a)

**Comment by krussedull** [comment]
how to manage this meenwhile? 
are we able to use images our self?
