### ISSUE TITLE
Server Installation Failed

### ISSUE THREAD

**Issue by DevRustic** [mr-guard/dayz-server-manager#147]
I have tried both docker and binary versions. Ubuntu 22.04 clean install (I've tried multiple times all on different systems)

`@2024-06-23T04:37:21.028Z | INFO      | SteamCMD     | Server Update Progress: verifying update: 90.13%
@2024-06-23T04:37:23.441Z | WARN      | Discord      | Queueing message because client did not start or is not yet ready [ false ]
@2024-06-23T04:37:23.451Z | ERROR     | Bootstrap    | Setup failed: Server installation failed [
  Error: Server installation failed
      at ManagerController.<anonymous> (/snapshot/dayz-server-manager/dist/control/manager-controller.js:215:27)
      at Generator.next (<anonymous>)
      at fulfilled (/snapshot/dayz-server-manager/dist/control/manager-controller.js:14:58)
]
`

**Comment by DevRustic** [comment]
Turns out i just had to change the serverExe config option from `"serverExe": "DayZServer_x64.exe",` to `"serverExe": "DayZServer",`

**Comment by jonni111** [comment]
Hi, did you make the tool work? Do you have a map displayed? Is the Discord bot working?
