### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by teddriq** [mr-guard/dayz-server-manager#16]
Hello, everything is working fine, but I want to know is there a way to set up 2 servers on 1 manager, or I need to make 1 manager per each server. 

And what is "Please use force_install_dir logon"  - am installing it okey, and all working, but Im keep getting that massage upon start.

**Comment by mr-guard** [comment]
Currently its not possible to manage multiple servers with a single manager instance.
This might change in the (near) future

You can ignore the "Please use force_install_dir logon" message
This is something about SteamCMD and not important for now
