### ISSUE TITLE
Man, I have a suggestion

### ISSUE THREAD

**Issue by Shuazijun** [mr-guard/dayz-server-manager#17]
The current program only has a single exe program. Can you release the web file of the management page to the directory where the program is located? In this way, users in different countries can manually modify the page and translate it, so as to support multilingual environment

**Comment by mr-guard** [comment]
Thanks for the suggestion.

Unfortunatly, I cannot ship the UI apart from the executable.
The path to the UI files is currently hardcoded and there is no plan to change that to keep the setup as minimalistic as possible.

However, I agree that proper multilanguage support should be built into the app.
This would require stringtable/i18n support to be added to the angular project.

Once that's done you are welcome to provide translations by opening a pull request.

**Comment by Shuazijun** [comment]
When will multilingualism be developed?

**Comment by mr-guard** [comment]
Currently I am working on a rewrite of the manager.
I will let you know as soon as I start to work on the UI for that

No ETA tho, unfortunatly.

Are there any translations which are especially important to you?

**Comment by Shuazijun** [comment]
Please test the compatibility of the application with simplified Chinese or traditional Chinese. It is known that Omega manager cannot recognize modules with simplified Chinese names due to coding problems Please pay attention
