### ISSUE TITLE
Not Work "Shows player and vehicle position on a map"

### ISSUE THREAD

**Issue by Kirill246** [mr-guard/dayz-server-manager#19]
Hi,players are not displayed on the map.
I replaced the old exe file with a new one. The map has appeared, but the players' location is not working.

**Comment by mr-guard** [comment]
Can you test again with version v2.1.3?

**Comment by Kirill246** [comment]
does not work, there is no display of cars and players on the map

**Comment by mr-guard** [comment]
Can you check if there are any errors shown in the server manager log or in the browser console?

**Comment by Kirill246** [comment]
I can send the full logs to the mail, maybe it will become clear what is wrong.

@2022-01-19T12:54:16.791Z | INFO      | Monitor    | Server running...
Unhandled Rejection: TypeError: Cannot read property 'length' of undefined
    at Connection.<anonymous> (C:\snapshot\dayz-server-manager\node_modules\@senfo\battleye\dist\lib\connection.js:126:53)
    at Generator.next (<anonymous>)
    at C:\snapshot\dayz-server-manager\node_modules\@senfo\battleye\dist\lib\connection.js:8:71
    at new Promise (<anonymous>)
    at C:\snapshot\dayz-server-manager\node_modules\@senfo\battleye\dist\lib\connection.js:4:12
    at Connection.recieve (C:\snapshot\dayz-server-manager\node_modules\@senfo\battleye\dist\lib\connection.js:123:16)
    at Socket.receive (C:\snapshot\dayz-server-manager\node_modules\@senfo\battleye\dist\lib\socket.js:114:37)
    at Socket.emit (events.js:376:20)
    at UDP.onMessage [as onmessage] (dgram.js:934:8)
Unhandled Rejection: TypeError: Cannot read property 'length' of undefined
    at Connection.<anonymous> (C:\snapshot\dayz-server-manager\node_modules\@senfo\battleye\dist\lib\connection.js:126:53)
    at Generator.next (<anonymous>)
    at C:\snapshot\dayz-server-manager\node_modules\@senfo\battleye\dist\lib\connection.js:8:71
    at new Promise (<anonymous>)
    at C:\snapshot\dayz-server-manager\node_modules\@senfo\battleye\dist\lib\connection.js:4:12
    at Connection.recieve (C:\snapshot\dayz-server-manager\node_modules\@senfo\battleye\dist\lib\connection.js:123:16)
    at Socket.receive (C:\snapshot\dayz-server-manager\node_modules\@senfo\battleye\dist\lib\socket.js:114:37)
    at Socket.emit (events.js:376:20)
    at UDP.onMessage [as onmessage] (dgram.js:934:8)


 8:03:22.651 Warning Message: '/' is not a value
8:03:22.682 DamageSystem Warning: Selection dmgZone_fuelTank doesn't exists in fire geometry for entity OffroadHatchback
8:03:22.682 Warning Message: No entry 'bin\config.bin/CfgVehicles/Car/Reflectors/Left.radius'.
8:03:22.682 Warning Message: '/' is not a value
8:03:22.682 Warning Message: No entry 'bin\config.bin/CfgVehicles/Car/Reflectors/Right.radius'.
8:03:22.682 Warning Message: '/' is not a value
8:03:22.704 Warning Message: Cannot open object dz\vehicles\proxies\bus_driver.p3d
8:03:22.704 Warning: No components in dz\vehicles\wheeled\offroadhatchback\proxy\nivaengine.p3d:geometry
8:03:22.704 Warning: No components in dz\vehicles\wheeled\offroadhatchback\proxy\nivaengine.p3d:geometryView
8:03:22.704 Warning Message: Cannot open object dz\vehicles\proxies\bus_cargo.p3d
8:03:22.936 Warning Message: No entry 'bin\config.bin/CfgVehicles/OffroadHatchback_Blue.viewDriverShadow'.
8:03:22.936 Warning Message: '/' is not a value
8:03:22.936 Warning Message: No entry 'bin\config.bin/CfgVehicles/OffroadHatchback_Blue.viewDriverShadowDiff'.
8:03:22.936 Warning Message: '/' is not a value
8:03:22.936 Warning Message: No entry 'bin\config.bin/CfgVehicles/OffroadHatchback_Blue.viewDriverShadowAmb'.
8:03:22.936 Warning Message: '/' is not a value
8:03:22.936 Warning Message: No entry 'bin\config.bin/CfgVehicles/OffroadHatchback_Blue.viewCargoShadow'.
8:03:22.936 Warning Message: '/' is not a value
8:03:22.936 Warning Message: No entry 'bin\config.bin/CfgVehicles/OffroadHatchback_Blue.viewCargoShadowDiff'.
8:03:22.936 Warning Message: '/' is not a value
8:03:22.936 Warning Message: No entry 'bin\config.bin/CfgVehicles/OffroadHatchback_Blue.viewCargoShadowAmb'.
8:03:22.936 Warning Message: '/' is not a value
8:03:22.936 DamageSystem Warning: Selection dmgZone_fuelTank doesn't exists in fire geometry for entity OffroadHatchback_Blue
8:03:22.936 Warning Message: No entry 'bin\config.bin/CfgVehicles/Car/Reflectors/Left.radius'.
8:03:22.936 Warning Message: '/' is not a value
8:03:22.936 Warning Message: No entry 'bin\config.bin/CfgVehicles/Car/Reflectors/Right.radius'.
8:03:22.936 Warning Message: '/' is not a value

**Comment by Kirill246** [comment]
I noticed that my file DayZServer\profiles\DayZServer_x64.ADM, DayZServer_x64_2022-02-08_22-28-58.RPT, script_2022-02-08_22-29-10.log is not updated, maybe it's somehow related.  But if you open these files, the information appears in them.

**Comment by kapatheus** [comment]
Is there a fix for this problem?

**Comment by uncle-ara** [comment]
> Is there a fix for this problem?

I think the developer abandoned this project

**Comment by mr-guard** [comment]
closing as it is really old
