### ISSUE TITLE
Can I leave a discord channel? I don't know how to use the process

### ISSUE THREAD

**Issue by AdmaXu** [mr-guard/dayz-server-manager#20]
Can I leave a discord channel? I don't know how to use the process

**Comment by mr-guard** [comment]
I don't understand what you mean.

Can you explain with more details on what you are trying to do?

**Comment by AdmaXu** [comment]
I go to the web backend and click on login but no response. I don't know if I did the installation steps wrong. Can you tell me the whole installation process? Thank you.

**Comment by mr-guard** [comment]
I am going to close this, as its really old.
If the issue persists, please open another one.
