### ISSUE TITLE
Add forbidden characters to folder name

### ISSUE THREAD

**Issue by m0v1l** [mr-guard/dayz-server-manager#21]
You have a replacement for prohibited signs. Add a ":" to this.
Mod example: https://steamcommunity.com/sharedfiles/filedetails/?id=1975926581 , this mod closes the application window without the error message "because the wrong mod folder is being created"

**Comment by mr-guard** [comment]
Thanks for the heads up.

I will add it asap

**Comment by mr-guard** [comment]
Should be fixed in v2.1.4

Please report back
