### ISSUE TITLE
Error reading ADM

### ISSUE THREAD

**Issue by fr1nk** [mr-guard/dayz-server-manager#22]
Hello there. First off, thanks for developing this tool, I appreciate it a lot. I'm setting up a new server for friends and everything appears to work fine, though I've seen this error a couple of times after a couple dozen manual/scheduled restarts:

```
@2022-01-26T13:00:52.559Z | INFO      | SteamCMD   | Skipping copy of mod (1559212036) dir because its already up to date
@2022-01-26T13:00:52.788Z | INFO      | SteamCMD   | Skipping copy of mod (1828439124) dir because its already up to date
@2022-01-26T13:00:52.789Z | INFO      | SteamCMD   | Skipping copy of mod (1597140327) dir because its already up to date
@2022-01-26T13:00:52.789Z | INFO      | SteamCMD   | Skipping copy of mod (1602372402) dir because its already up to date
@2022-01-26T13:00:52.790Z | INFO      | SteamCMD   | Skipping copy of mod (1891132304) dir because its already up to date
@2022-01-26T13:00:52.792Z | INFO      | SteamCMD   | Copying @Winter-Deer-Isle key ASC_WinterDeerIsle.bikey
@2022-01-26T13:00:52.793Z | INFO      | SteamCMD   | Copying @VPPAdminTools key VPP.bikey
@2022-01-26T13:00:52.794Z | INFO      | SteamCMD   | Copying @CF key Jacob_Mango_V3.bikey
@2022-01-26T13:00:52.796Z | INFO      | SteamCMD   | Copying @Winter-Chernarus key Crazymike_winterchernarus.bikey
@2022-01-26T13:00:52.799Z | INFO      | SteamCMD   | Copying @DeerIsle key deerisle45.bikey
@2022-01-26T13:00:53.172Z | WARN      | LogReader  | Error reading ADM [
  "size check for C:\\Servers\\DayZSADeerIsle\\DayZServer\\profiles\\DayZServer_x64.ADM failed: Error: ENOENT: no such file or directory, stat 'C:\\Servers\\DayZSADeerIsle\\DayZServer\\profiles\\DayZServer_x64.ADM'"
]
Press any key to continue . . .
```

Manual restart worked fine after encountering this error. Am not sure if this is a config issue on my end or an actual issue somewhere else. Thanks for reviewing.

**Comment by mr-guard** [comment]
Thanks for the report!

Indeed, there is an issue with how the file is read under certain circumstances:

The manager tries to read the file just after the old adm log is deleted and the new one is created
Not much I can do about that, since it is handled in the library used for that, but I will prevent the error from crashing the app.

**Comment by mr-guard** [comment]
closing as it is really old

**Comment by defib** [comment]
This error happens every other day for me, almost always after the 12am server restart. 

Is there any work towards this? Can you catch the stack trace and re-try?

**Comment by mr-guard** [comment]
I havent encountered this error since months
Are you on the latest version of the manager?

**Comment by defib** [comment]
I am on 3.4.0

**Comment by mr-guard** [comment]
I will have a look then

**Comment by defib** [comment]
It's pretty much happening daily now fyi, there don't seem to be any stack traces

**Comment by defib** [comment]
Looks all fixed as of the latest version, you can close this
