### ISSUE TITLE
Press any key to continue . . .

### ISSUE THREAD

**Issue by AdmaXu** [mr-guard/dayz-server-manager#25]
@2022-03-27T18:46:38.719Z | IMPORTANT | Manager    | Starting DZSM Version: 2.1.1
@2022-03-27T18:46:38.721Z | IMPORTANT | Config     | Trying to read config at: C:\Users\Wendy\Desktop\server-manager\build\server-manager.json
@2022-03-27T18:46:38.723Z | IMPORTANT | Config     | Successfully read config
@2022-03-27T18:46:38.724Z | INFO      | Database   | Database Setup: node 14.17.0 : v83-win32-x64
@2022-03-27T18:46:39.310Z | IMPORTANT | Requiremen |

Firewall rules were not found.
You can add the rules manually or by running the following command in a elevated command promt:

netsh firewall add allowedprogram C:\Users\Wendy\Desktop\server-manager\build\DayZServer\DayZServer_x64.exe DayZ ENABLE

@2022-03-27T18:46:40.370Z | IMPORTANT | Manager    | Initially checking SteamCMD, Server Installation and Mods. Please wait. This may take some minutes...
@2022-03-27T18:46:40.371Z | IMPORTANT | SteamCMD   | Checking/Installing SteamCMD
Redirecting stderr to 'C:\Users\Wendy\Desktop\server-manager\build\SteamCMD\logs\stderr.txt'
[  0%] 正在检查可用更新...
[----] 正在验证安装...
Steam Console Client (c) Valve Corporation - version 1648077083
-- type 'quit' to exit --
Loading Steam API...OK

Redirecting stderr to 'C:\Users\Wendy\Desktop\server-manager\build\SteamCMD\logs\stderr.txt'
[  0%] 正在检查可用更新...
[----] 正在验证安装...
Steam Console Client (c) Valve Corporation - version 1648077083
-- type 'quit' to exit --
Loading Steam API...OK
Logging in user 'az238131f1s4' to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Please use force_install_dir before logon!
 Update state (0x5) verifying install, progress: 12.13 (13700360 / 112911848)
 Update state (0x5) verifying install, progress: 17.37 (491317144 / 2828919141)
 Update state (0x5) verifying install, progress: 41.39 (1170768221 / 2828919141)
 Update state (0x5) verifying install, progress: 66.82 (1890367285 / 2828919141)
 Update state (0x5) verifying install, progress: 92.43 (2614665368 / 2828919141)
Success! App '223350' fully installed.

@2022-03-27T18:46:56.438Z | IMPORTANT | REST       | App listening on the http://127.0.0.1:2313
@2022-03-27T18:47:17.502Z | ERROR     | Manager    | connect ETIMEDOUT 69.171.229.11:443 [
  Error: connect ETIMEDOUT 69.171.229.11:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
    errno: -4039,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '69.171.229.11',
    port: 443,
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET /api/v7/gateway HTTP/1.1\r\n' +
        'Host: discordapp.com\r\n' +
        'Authorization: ODk4NjAxODU0ODczNzg4NDM2.YWmmMQ.YF0E-OVkqqm84xuQYBf5tASROB4\r\n' +
        'User-Agent: DiscordBot (https://github.com/discordjs/discord.js, 11.6.4) Node.js/v14.17.0\r\n' +
        'Accept-Encoding: gzip, deflate\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/v7/gateway',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'discordapp.com',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    }
  }
]
Press any key to continue . . .

**Comment by mr-guard** [comment]
I am going to close this, as its really old.
If the issue persists, please open another one.
