### ISSUE TITLE
[SUGGESTION] Rate limit exceeded avoidance

### ISSUE THREAD

**Issue by Kurosar** [mr-guard/dayz-server-manager#28]
Hello!

To avoid getting the "rate limit exceeded" error on steam (servers with big workshop list have that issue pretty often)
I believe you could use the "anonymous" user with no password on steamcmd, this user can download workshop items with no rate limit I think.

And for the server install/download, keep your regular steam username/password.

**Comment by mr-guard** [comment]
That's not an option with DayZ

You need to be logged in with an account which owns DayZ to be able to download mods

**Comment by Kurosar** [comment]
Well I just did a test and workshop works with the anonymous account, you need the account owning dayz only for the server download.

**Comment by radixtenshi** [comment]
any progress with this?

**Comment by radixtenshi** [comment]
i config the anonymous user on the SteamCDM and works as @Kurosar says.

**Comment by mr-guard** [comment]
see #48
