### ISSUE TITLE
Server Reverting edited values to default

### ISSUE THREAD

**Issue by m0edev** [mr-guard/dayz-server-manager#29]
Hi!

When you edit anything in the mpmission folder and restart the server it replaces everything that you have edited with the default values.

**Comment by mr-guard** [comment]
This appears to be an issue with steams app validation

**Comment by Kilgoreb29** [comment]
Mine also reverts my cfgeconomycore.xml back to stock. Also it seems I cant get the types to work in the server manager.

**Comment by mr-guard** [comment]
Just for the record:

This is not an issue with the manager but with steams server/client validation:
To fix it change the name of your mission folder to something other than dayzoffline.chernarusplus (or whatever the default is)

hint: make sure to also change the mission name in the server.cfg

**Comment by sotnikoff** [comment]
same problem here, renaming causes error

**Comment by onlinylee** [comment]
https://github.com/mr-guard/dayz-server-manager/issues/29#issuecomment-1114611995

**Comment by mr-guard** [comment]
@onlinylee you either need to change the mission name or disable server validation

**Comment by onlinylee** [comment]
> @onlinylee you either need to change the mission name or disable server validation
![image](https://github.com/mr-guard/dayz-server-manager/assets/90897703/6ce3168f-a233-46dc-9970-9303d8dc5d15)
Excuse me, Sir, do you mean the name of this place?

**Comment by mr-guard** [comment]
exactly

make sure its the same name as the mission folder
