### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gurulea93** [mr-guard/dayz-server-manager#31]
@mr-guard 
![Error](https://user-images.githubusercontent.com/23024161/169683347-be83fff7-df4a-4f0a-a3bc-6f1381377102.png)
I have this error, help me please

**Comment by buzzs125** [comment]
Remove your passwords from your server-manager.json file, and I can see if I can help you

**Comment by PhoenixSheppy** [comment]
If you're editing the JSON directly via Notepad you'll get this issue.

I had to write all changes in VSCode / Notepad++ to keep JSON formatting.

@gurulea93 Try doing this and report back.

**Comment by gurulea93** [comment]
I solved it, thank you
