### ISSUE TITLE
Map does not work

### ISSUE THREAD

**Issue by hemn6vyr** [mr-guard/dayz-server-manager#32]
Hi, I have some problems with map, it does hot work)
It does not show players and vehs
![image](https://user-images.githubusercontent.com/71910089/173896160-bae04e94-25fc-4b77-bd76-3fc8da4727ef.png)

**Comment by uncle-ara** [comment]
+

**Comment by 60plus** [comment]
Same issue. Map doesn't show players and vehicles

**Comment by H3liumCat** [comment]
Same here!

**Comment by MATTvanEAGLE** [comment]
Same here. And for the worse, if the server is set up to run Livonia / Enoch it does not even show the map at all!

**Comment by sarteko** [comment]
Has anyone found the solution?

**Comment by mr-guard** [comment]
should work now

closing as it is really old
