### ISSUE TITLE
Types editor does not show any files

### ISSUE THREAD

**Issue by 60plus** [mr-guard/dayz-server-manager#33]
Types editor does not show any files
![obraz](https://user-images.githubusercontent.com/73450566/175826816-2eae997b-22ad-4485-ac51-0b578c312a4f.png)

**Comment by H3liumCat** [comment]
Same here!

**Comment by Leander91** [comment]
I have the same problem.

**Comment by innoSYS-Project** [comment]
And me

**Comment by mr-guard** [comment]
closing as it is really old

**Comment by yuv41** [comment]
Has this been fixed? Its happening to me aswell
