### ISSUE TITLE
Cant Find Server

### ISSUE THREAD

**Issue by LxSTx** [mr-guard/dayz-server-manager#34]
Hey, so i hosted my server before without any "tools" like this, just basic start.bat etc. everything where workin fine.
now i found this awesome manager here (iam for real, u did a great job with that)
and now i got the problem that i cant find my server anymore. any ideas? :D

**Comment by mr-guard** [comment]
Porbably the server and/or the steam port is not opened in the firewall.

However, I am going to close this, as its really old.
If the issue persists, please open another one.
