### ISSUE TITLE
 the tool does not automatically download the MOD. please help me

### ISSUE THREAD

**Issue by DDosDayz** [mr-guard/dayz-server-manager#35]
I used it for the first time, but I tried so many times
![image](https://user-images.githubusercontent.com/91437513/179425608-1db71612-2bfe-451f-873b-782fc4d88338.png)

**Comment by Dev-Time** [comment]
In order to download workshop mods you need to use a steam account that owns DayZ.

**Comment by radixtenshi** [comment]
And the mod you want to download must be public or not-listed at least.

**Comment by mr-guard** [comment]
I am going to close this. If the issue persists open a followup issue
