### ISSUE TITLE
Adding events

### ISSUE THREAD

**Issue by VAN6661** [mr-guard/dayz-server-manager#36]
Hello!
Sorry for my English, I'm using a translator.

There is a problem with the display of Russian characters in the game ... there is some kind of limit on the number of characters, or I don’t know what ...
"params": [
             "Here the text is in Russian letters..."
The message in the game is displayed partially ... if you write in English characters - everything is fine!

**Comment by VAN6661** [comment]
for example...

"name": "2",
         "type": "message",
         "cron": "0/15 * * * *",
         "params": [
             "Добро пожаловать на сервер!"

In the game, this message is displayed as "Добро пожало" :(

**Comment by mr-guard** [comment]
closing as it is too old
if the issue is still there, let me know
