### ISSUE TITLE
won't start

### ISSUE THREAD

**Issue by GiRFace** [mr-guard/dayz-server-manager#37]
First time trying to start the server manager up and it stops here
![Screenshot 2022-08-17 153305](https://user-images.githubusercontent.com/34712670/185147229-e87bd856-a8c6-41ae-b4d7-51ecb2cf8cad.png)

I've only used notepad++ to edit the server-manager.json
Any ideas?

**Comment by xcpep** [comment]
You need to make sure the JSON file is correctly formatted.

Looks like you might have a rogue **W** character somewhere in the file.

**Comment by GiRFace** [comment]
> You need to make sure the JSON file is correctly formatted.
> 
> Looks like you might have a rogue **W** character somewhere in the file.

I thought something was off as well so i tested with a fresh copy of the original file and set things up, still get the same exact thing. i cant even verify the original JSON, it doesnt pass.

**Comment by xcpep** [comment]
Can you post the JSON here? Just change any sensitive pieces such as Discord keys, server passwords.

Cheers!

**Comment by mr-guard** [comment]
closing as it is really old
