### ISSUE TITLE
Unable to login to steamCMD

### ISSUE THREAD

**Issue by jackdaniels552** [mr-guard/dayz-server-manager#39]
I entered my login details to start the server manager and it keeps failing. I have logged in manually with the steamCMD and logged in with no issues but it still says invalid password even changed the password.

**Comment by mr-guard** [comment]
This can be the case if the password contains some exotic letters.
Try using just a-zA-Z0-9 (when in doubt increase the length of the password to ensure security)

However, I am going to close this, as its really old.
If the issue persists, please open another one.
