### ISSUE TITLE
Failure to copy Mod Keys

### ISSUE THREAD

**Issue by ntjohnst** [mr-guard/dayz-server-manager#40]
![Capture6](https://user-images.githubusercontent.com/6242372/192365078-95408381-4406-4556-8ff5-470eb62a72b7.PNG)

I am having an issue the launcher randomly fails to properly copy the mod keys saying that the resource is locked or in use.

**Comment by ntjohnst** [comment]
This problem is caused by having mods with the same key name, usually because its the same author.  Just delete one of the duplicate keys and the problem will be resolved.

**Comment by mr-guard** [comment]
fixed
