### ISSUE TITLE
crash server manager

### ISSUE THREAD

**Issue by RemMajiTensh1** [mr-guard/dayz-server-manager#44]
about once a day crash "server-manager"
I can’t understand the reason, because during the day the restarts are normal, but when I go to check in the morning, the program no longer works and I have to start it again.
the server itself is running
![image](https://user-images.githubusercontent.com/120824638/208257355-db74b393-e25d-44bd-b3ab-ff5c791de6a9.png)

**Comment by radixtenshi** [comment]
That problem is related to the DayzServer_x64.ADM log file. Probably the file is growing too much or at some point it cannot be written and the manager crashes. Try deleting all log files and see how the server starts

**Comment by mr-guard** [comment]
Should be fixed
closing as it is really old
