### ISSUE TITLE
Every mod is asking for mobile authentification

### ISSUE THREAD

**Issue by GameAreaCZ** [mr-guard/dayz-server-manager#46]
Every mod is asking for mobile authentification it does not cached so it is like unusable

**Comment by john2151** [comment]
Had the same problem. Worked around it by disabling Steam Guard on my mobile device, so back to e-mail based 2FA.
Interestingly enough that fixed the issue, since this authorization is (apparently) permanent

**Comment by EvanKnowles** [comment]
Mine then hit some rate limit from the repeated login attempts, none of which were unsuccesful:

Logging in user ''  to Steam Public...FAILED (Rate Limit Exceeded)

**Comment by mr-guard** [comment]
If you have too many mods listed then the rate limit will occur.
The main reason is that the manager tries to download each mod independently

To circumwent this, installing mods in batches should work.
Might as well check the steam api whether the mod has been updated, this way the steamcmd doesnt even need to be invoked

**Comment by mr-guard** [comment]
related to #48

**Comment by mr-guard** [comment]
see #48
