### ISSUE TITLE
Steam temporary banned my user.

### ISSUE THREAD

**Issue by radixtenshi** [mr-guard/dayz-server-manager#48]
The manager connect and login one time for each mod to check or download the update on the start process.
If you have a lot of mods it connects a lot of times in one minute. That result in a temporary ban of the account.

Is any way of avoit that? i get banned everytime i run an update.

**Comment by john2151** [comment]
Same problem here
Getting "Rate limit exceeded"

**Comment by mr-guard** [comment]
The manager tries to download mods one after another instead of in batches (in order to prevent timeouts)
if you have many mods, then the rate limit occurs

I might need to implement downloading in batches again

**Comment by mr-guard** [comment]
batch downloads and checks for updates are now implemented, so this can be circumvented

closing as fixed
