### ISSUE TITLE
Server Starts but doesn't show on LAN

### ISSUE THREAD

**Issue by fsaenz02** [mr-guard/dayz-server-manager#50]
My server starts and shows running with 0 players. When I try to connect to the server it doesnt show anything under LAN in the launcher. I see options for changing the port in the config file but I dont see anywhere for the ip address. Its running on localhost so I assumed that it would just show up in the launcher but no luck. Does anyone know how to connect to it if it isnt coming up under LAN in the launcher? I also tried looking withing steam under view>servers>lan and still nothing. Any help would be appreciated! Thank you!
![Capture](https://user-images.githubusercontent.com/93811487/233090173-4f2dd719-c454-4c26-b914-799132c56410.PNG)
![Capture1](https://user-images.githubusercontent.com/93811487/233090208-c4dcfccd-a374-4a63-a680-99fc1085ccf2.PNG)

**Comment by radixtenshi** [comment]
you will not see the server in the server browser if the ports are not open in your windows firewall and in your router firewall, specially the "steamQueryPort": 2305. Because the server cant connect to the Bohemia Server List.
i asume you still can connect via LAN from the same machine using the ip 127.0.0.1:2302 (if 2302 is your game port).

**Comment by mr-guard** [comment]
probably as described above

@radixtenshi thanks for sharing the info

I am going to close this. If the issue persists open a followup issue or comment to reopen this one

**Comment by Wuest3nFuchs** [comment]
Had exactly the same issue the server was not reachable with the port given 2305 in the servermanager.json.
Tried 27016 and it showed up a few seconds after starting up the server.
Have a nice weekend Survivors
