### ISSUE TITLE
WebUI 

### ISSUE THREAD

**Issue by BreathXV** [mr-guard/dayz-server-manager#52]
What is the recommended way to setup the WebUI so I can access it from other laptops and such?

**Comment by mr-guard** [comment]
The WebUI can be exposed by using a reverse proxy (such as nginx).

You could install nginx on the server and then create a location which uses proxy_pass to forward the requests to the server manager api listening on localhost.

You can also enable "publishWebserver". This will make the webserver listen for external traffic.


In either case make sure the firewall is allowing traffic to the webserver

**Comment by BreathXV** [comment]
> The WebUI can be exposed by using a reverse proxy (such as nginx).
> 
> You could install nginx on the server and then create a location which uses proxy_pass to forward the requests to the server manager api listening on localhost.
> 
> You can also enable "publishWebserver". This will make the webserver listen for external traffic.
> 
> In either case make sure the firewall is allowing traffic to the webserver

I appreciate the response.
