### ISSUE TITLE
NOT AN ISSUE, But a posible Request

### ISSUE THREAD

**Issue by radixtenshi** [mr-guard/dayz-server-manager#53]
First of all, I congratulate you on the development of the tool. I've had it "on" 24 hours a day for more than a year and the problems I've had are almost always related to the game or steamcmd but not to the manager.

That being said, I want to propose, if the code is updated, and if it is possible to add a small functionality:

- The possibility that when the manager detects that the dayz is not running, before starting it, that a script can be defined to be executed and possibly a time between each execution (script, game).

The reason for this is that, in cases where the manager is not used and the server is executed through a batch file in the traditional way, when the server performs the restart process, tasks such as deleting logs, file renaming (for randomizing traders and dynamic events) and other tasks that qheny you are using the manager is not possible since it runs the game directly.

If it was possible to define a series of batch files, I say batch because it is the most basic and simple, but it could be any type of script. And also a timeout between executions, or a stdout, so it is possible to add or remove maintenance scripts that run before the manager starts the game again during the reboot process.

I don't know if I explained myself well, but it would be great to add a functionality of this type.

Thank you and again congratulations for the great job.

**Comment by mr-guard** [comment]
Thanks for the kind words :)

Adding hooks is already possible.
In the server manager config add a hook object to the hooks array like so:

```json
...
"hooks": [
  {
    "type": "beforeStart",
    "program": "path\\to\\your\\script.bat"
  }
],
...
```
This will start the script before the server starts and waits for the script to complete.
You can also add multiple hooks of the same type which will be called in the order they are listed.

If the manger does not start the bat, you might need to use cmd.exe as program and pass the script as a parameter
```json
...
"hooks": [
  {
    "type": "beforeStart",
    "program": "cmd.exe",
    "params": ["/c", "path\\to\\your\\script.bat"]
  }
],
...
```

(the `/c` is needed to invoke bat script)

**Comment by mr-guard** [comment]
closing as it is implemeted and now documented
