### ISSUE TITLE
Server Is Not Starting

### ISSUE THREAD

**Issue by SLBlackHatMan** [mr-guard/dayz-server-manager#56]
![image](https://github.com/mr-guard/dayz-server-manager/assets/68303323/774a6b8b-9993-4c51-9cbf-56a872a38db2)

**Comment by mr-guard** [comment]
Looks like the manager crashed/was stopped..
But I cannot tell what's wrong from the screenshot.

Please provide more info on what's wrong.
Is the manager crashing or is the DayZ server not starting?

**Comment by mr-guard** [comment]
This seems to be a bug with discord actually.
If a "invalid" discord token is added the manager crashes without any trace.

Sometimes the same token will work after some time but I have no clue why this is happening.
Removing the discord token will help but ofc disable the discord bot.

**Comment by mr-guard** [comment]
This was caused by the new discord chanel types which were not correctly handles by the discord client lib. It should be fixed in v3.6.0
