### ISSUE TITLE
Stuck at Checking/Installing SteamCMD

### ISSUE THREAD

**Issue by loggi555** [mr-guard/dayz-server-manager#58]
![image](https://github.com/mr-guard/dayz-server-manager/assets/143316058/3f6990d4-c1ab-4c65-ba07-8d5e14b5f5bf)

Ive had an ark server on this machine before that also used steamcmd. Ive deleted the SteamCMD folder there
For some reason it gets stuck right here and the process isnt really doing anything.

Ive made sure that the antivirus lets the script do its thing.

**Comment by loggi555** [comment]
![image](https://github.com/mr-guard/dayz-server-manager/assets/143316058/077aad7f-a064-4959-8a9a-be9ca4a197a7)

**Comment by mr-guard** [comment]
The dayz server can not be downloaded with the 'anonymous' user.
The server download itself just needs a valid steam user (iirc), when downloading mods, the account also need to own the dayz base game

**Comment by loggi555** [comment]
> 

Yeah i noticed now The Problem is that i exceeded my RateLimit because i have two factor enabled. I have now disabled it and need to wait a bit before i can retry to login. I think I login first running steam cmd manually, and then run the script. If that works it may be worth adding it to the user guide. Because on LogLevel 1 you dont see the problem. thanks for your help!

**Comment by loggi555** [comment]
> The dayz server can not be downloaded with the 'anonymous' user. The server download itself just needs a valid steam user (iirc), when downloading mods, the account also need to own the dayz base game
> 
> Was the manager really getting stuck at installing the steam cmd or was it just taking some time?

I would be down to help enhance the users guide when i get it running - because the 2fa

**Comment by mr-guard** [comment]
Would gladly appreciate it

**Comment by onlinylee** [comment]
@loggi555 Did you find the problem?

**Comment by lapochka8** [comment]
@2023-09-28T00:44:04.151Z | ERROR     | Bootstrap    | ENOENT: no such file or directory, open 'C:\Users\admin\Desktop\server-manager-windows\DayZServer\profiles\DZSMApiOptions.json' [
  Error: ENOENT: no such file or directory, open 'C:\Users\admin\Desktop\server-manager-windows\DayZServer\profiles\DZSMApiOptions.json'
      at Object.openSync (node:fs:585:3)
      at Object.openSync (pkg/prelude/bootstrap.js:793:32)
      at Object.writeFileSync (node:fs:2170:35)
      at IngameREST.<anonymous> (C:\snapshot\dayz-server-manager\dist\interface\ingame-rest.js:62:21)
      at Generator.next (<anonymous>)
      at C:\snapshot\dayz-server-manager\dist\interface\ingame-rest.js:22:71
      at new Promise (<anonymous>)
      at C:\snapshot\dayz-server-manager\dist\interface\ingame-rest.js:18:12
      at IngameREST.start (C:\snapshot\dayz-server-manager\dist\interface\ingame-rest.js:52:16)
      at ManagerController.<anonymous> (C:\snapshot\dayz-server-manager\dist\control\manager-controller.js:149:35) {
    errno: -4058,
    syscall: 'open',
    code: 'ENOENT',
    path: 'C:\\Users\\admin\\Desktop\\server-manager-windows\\DayZServer\\profiles\\DZSMApiOptions.json'
  }
]
Press any key to continue . . .

**Comment by lapochka8** [comment]
fixed it, had to run as administrator.

**Comment by mr-guard** [comment]
I will mark this as resolved
