### ISSUE TITLE
Adding BEC,  Not a Issue

### ISSUE THREAD

**Issue by Setman590** [mr-guard/dayz-server-manager#59]
Is there a way to add BEC to also start? (BattlEye-Extended-Controls)

**Comment by mr-guard** [comment]
You can use hooks to start BEC on server start.

However, most of the things BEC does can be done with the server manager (events in the config files) directly

Are you missing some features from BEC?

**Comment by Setman590** [comment]
Ok cool, just starting setting this up, have not looked around in the Panel yet.
