### ISSUE TITLE
Using -ip parameter

### ISSUE THREAD

**Issue by jacobianb** [mr-guard/dayz-server-manager#60]
I tried setting 

"serverLaunchParams": [-ip 192.168.1.117],

This resulted in invalid json, so I tried 

"serverLaunchParams": ["-ip 192.168.1.117"],

This resulted in valid json, however, the ip would not bind to my local address. It was still binding to 0.0.0.0 when checked through netstat. This makes it add the launch parameter with quotes around it and I think in order for it to bind successfully to a specific ip perhaps it needs to be specified before -port, meaning you'd have to add a provision for the -ip parameter into your configuration. Maybe I'm just doing it incorrectly, please let me know! Thank you.

**Comment by mr-guard** [comment]
Did you solve the issue?

What caused it?
