### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by loander** [mr-guard/dayz-server-manager#63]
Hello there im trying to set this up for the first time and im getting this error:
![image](https://github.com/mr-guard/dayz-server-manager/assets/25728927/5990f1b2-4259-4a39-8427-94daf0bec01b)

**Comment by mr-guard** [comment]
There is an error in the config parser currently.

Remove the following line from the config:
"mapHost": "https://mr-guard.de/dayz-maps",

I am already working on it

**Comment by guilhermesferreira** [comment]
Hello,
I got the same error when assigning discord token.
Leaving the field blank, it starts the srv normally.
Thanks for the excellent work

**Comment by dkoz** [comment]
You get similar error assigning discord token. The server just won't start and you're prompted to close out out of the window.

**Comment by guilhermesferreira** [comment]
> You get similar error assigning discord token. The server just won't start and you're prompted to close out of the window.

exactly

**Comment by loander** [comment]
Also when adding mods to the config same thing happens. Seems like as soon as new lines are added in the file it just breaks

**Comment by mr-guard** [comment]
should be fixed in version v3.2.0

Could you provide feedback if there are any issues?

**Comment by guilhermesferreira** [comment]
![image](https://github.com/mr-guard/dayz-server-manager/assets/45656415/23aaf3cb-ecc7-4381-9fd1-80a56c298af1)
I'll check if it was my mistake, but in the token it gives an error, but it passed and didn't lock the console
