### ISSUE TITLE
execution via vscode

### ISSUE THREAD

**Issue by guilhermesferreira** [mr-guard/dayz-server-manager#65]
Hello, if it's not too much to ask, could you insert instructions for running the server other than the already compiled version? to run directly through vscode?

**Comment by mr-guard** [comment]
Have a look at the [README > Development](https://github.com/mr-guard/dayz-server-manager#development-)

This shows how to run the app via npm

You can add a vscode start script that just executes npm start

**Comment by mr-guard** [comment]
Since there were no further questions, I will mark this as resolved
