### ISSUE TITLE
Request Seam ID in player list

### ISSUE THREAD

**Issue by penalte** [mr-guard/dayz-server-manager#67]
Can you please add steamID64 in player list?

Thank you for this amazing project.

**Comment by mr-guard** [comment]
I will need to check if I can get the id via RCON but I dont think so.
The playerlist is provided by rcon and I would somehow need to match the rcon entry to the ingame player entity. Dunno if thats possible in a reliable way

**Comment by mr-guard** [comment]
this has been added in v3.5.0
