### ISSUE TITLE
This is not a bug, but a suggestion

### ISSUE THREAD

**Issue by guilhermesferreira** [mr-guard/dayz-server-manager#69]
Hello dev!
Once again, congratulations on the incredible work!
I would like to make a suggestion... it would be great to include some more filters on the map, perhaps by item type?

You could also create a discord to interact with people, this project has a TOP future...

Hello dev!
Once again, congratulations on the incredible work!
I would like to make a suggestion... it would be great to include some more filters on the map, perhaps by item type?

You could also create a discord to interact with people, this project has a TOP future

I remain at your disposal for any feedback, topics or exchange of ideas! (Discord: g.siqueira)

**Comment by mr-guard** [comment]
Sorry for the late reply

Indeed, a map filter would be helpful

There already is a discord server about the server manager. You can find it in the readme (the chat button right at the top)

**Comment by mr-guard** [comment]
this has been added in v3.5.0
