### ISSUE TITLE
After mounting mods will crash and exit

### ISSUE THREAD

**Issue by onlinylee** [mr-guard/dayz-server-manager#72]
### After mounting mods, [dayz-server-manager] has not been able to start smoothly, it will crash and exit, occasionally can launch, I don't know why.

**Log as follows:**
@2023-10-08T10:36:15.540Z | IMPORTANT | Manager      | Starting DZSM Version: 3.3.0 - []
@2023-10-08T10:36:15.542Z | INFO      | Database     | Database Setup: node 16.16.0 : v93-win32-x64 - []
@2023-10-08T10:36:15.545Z | IMPORTANT | Config       | Trying to read config at: E:\DayZ789\server-manager.json - []
@2023-10-08T10:36:15.555Z | IMPORTANT | Config       | Successfully read config - []
@2023-10-08T10:36:16.458Z | IMPORTANT | Requirements | 

Firewall rules were not found.
You can add the rules manually or by running the following command in a elevated command promt:

netsh advfirewall firewall add rule name="DayZ" dir=in action=allow program="E:\DayZ789\DayZServer\DayZServer_x64.exe" enable=yes

Legacy alternative: netsh firewall add allowedprogram E:\DayZ789\DayZServer\DayZServer_x64.exe DayZ ENABLE - []
@2023-10-08T10:36:16.750Z | IMPORTANT | Bootstrap    | Initially checking SteamCMD, Server Installation and Mods. Please wait. This may take some minutes... - []
@2023-10-08T10:36:16.751Z | IMPORTANT | SteamCMD     | Checking/Installing SteamCMD - []
@2023-10-08T10:36:17.190Z | INFO      | SteamCMD     | Progress:   0% - Checking for available updates... - []
@2023-10-08T10:36:17.692Z | INFO      | SteamCMD     | Progress: ---- - Verifying installation... - []
@2023-10-08T10:36:28.563Z | INFO      | SteamCMD     | Server Update Progress: verifying install: 5.58% - []
@2023-10-08T10:36:30.035Z | INFO      | SteamCMD     | Server Update Progress: verifying install: 18.61% - []
@2023-10-08T10:36:32.024Z | INFO      | SteamCMD     | Server Update Progress: verifying install: 43.15% - []
@2023-10-08T10:36:34.019Z | INFO      | SteamCMD     | Server Update Progress: verifying install: 68.45% - []
@2023-10-08T10:36:36.045Z | INFO      | SteamCMD     | Server Update Progress: verifying install: 94.30% - []

### If don't load any mods all going well.

**Log as follows:**
@2023-10-08T10:34:53.385Z | IMPORTANT | Manager      | Starting DZSM Version: 3.3.0 - []
@2023-10-08T10:34:53.387Z | INFO      | Database     | Database Setup: node 16.16.0 : v93-win32-x64 - []
@2023-10-08T10:34:53.390Z | IMPORTANT | Config       | Trying to read config at: E:\DayZ789\server-manager.json - []
@2023-10-08T10:34:53.398Z | IMPORTANT | Config       | Successfully read config - []
@2023-10-08T10:34:54.343Z | IMPORTANT | Requirements | 

Firewall rules were not found.
You can add the rules manually or by running the following command in a elevated command promt:

netsh advfirewall firewall add rule name="DayZ" dir=in action=allow program="E:\DayZ789\DayZServer\DayZServer_x64.exe" enable=yes

Legacy alternative: netsh firewall add allowedprogram E:\DayZ789\DayZServer\DayZServer_x64.exe DayZ ENABLE - []
@2023-10-08T10:34:54.632Z | IMPORTANT | Bootstrap    | Initially checking SteamCMD, Server Installation and Mods. Please wait. This may take some minutes... - []
@2023-10-08T10:34:54.633Z | IMPORTANT | SteamCMD     | Checking/Installing SteamCMD - []
@2023-10-08T10:34:55.040Z | INFO      | SteamCMD     | Progress:   0% - Checking for available updates... - []
@2023-10-08T10:34:55.562Z | INFO      | SteamCMD     | Progress: ---- - Verifying installation... - []
@2023-10-08T10:35:06.601Z | INFO      | SteamCMD     | Server Update Progress: verifying install: 4.65% - []
@2023-10-08T10:35:08.031Z | INFO      | SteamCMD     | Server Update Progress: verifying install: 17.98% - []
@2023-10-08T10:35:10.049Z | INFO      | SteamCMD     | Server Update Progress: verifying install: 42.05% - []
@2023-10-08T10:35:12.000Z | INFO      | SteamCMD     | Server Update Progress: verifying install: 66.39% - []
@2023-10-08T10:35:14.046Z | INFO      | SteamCMD     | Server Update Progress: verifying install: 91.49% - []
@2023-10-08T10:35:15.174Z | IMPORTANT | Monitor      | Starting to watch server - []
@2023-10-08T10:35:15.174Z | WARN      | Discord      | Not starting discord bot, because no bot token was provided - []
@2023-10-08T10:35:15.178Z | IMPORTANT | RCON         | Listening on 0.0.0.0:64258 - []
@2023-10-08T10:35:15.179Z | IMPORTANT | REST         | App listening on the http://127.0.0.1:80 - []
@2023-10-08T10:35:15.182Z | IMPORTANT | IngameREST   | Ingame Rest API listening on the http://127.0.0.1:2312 - []
@2023-10-08T10:35:15.182Z | IMPORTANT | Bootstrap    | Server Manager initialized successfully - []
@2023-10-08T10:35:15.183Z | IMPORTANT | Bootstrap    | Waiting for first server monitor tick.. - []
@2023-10-08T10:35:15.976Z | IMPORTANT | Monitor      | Server not found. Starting... - []
@2023-10-08T10:35:16.028Z | INFO      | ServerStarte | Writing server cfg - []
@2023-10-08T10:35:16.030Z | INFO      | ServerStarte | Adjusting dayzsetting.xml - []
@2023-10-08T10:35:17.177Z | INFO      | IngameReport | Server sent ingame report: 0 players, 43 vehicles - []

**Mods as follows:**
**All mods have been downloaded, and server is running successfully, and I can join the game**

  "steamWsMods": [
    {
      "name": "CF",
      "workshopId": "1559212036"
    },
    {
      "name": "VPPAdminTools",
      "workshopId": "1828439124"
    },
    {
      "name": "ZomBerry Admin Tools",
      "workshopId": "1582756848"
    },
    {
      "name": "SIX-DayZ-Auto-Run",
      "workshopId": "1781132597"
    },
    {
      "name": "Unlimited Stamina",
      "workshopId": "1560819773"
    },
    {
      "name": "BaseBuildingPlus",
      "workshopId": "1710977250"
    },
    {
      "name": "BBPItemPack",
      "workshopId": "2794690371"
    },
    {
      "name": "VanillaPlusPlusMap",
      "workshopId": "1623711988"
    },
    {
      "name": "GasMasksOnly",
      "workshopId": "2621103156"
    },
    {
      "name": "RaG_BaseItems",
      "workshopId": "2878980498"
    },
    {
      "name": "RaG Vehicle Pack",
      "workshopId": "2880254695"
    },
    {
      "name": "MMG Country Camo Extension",
      "workshopId": "2802653896"
    },
    {
      "name": "MMG - Mightys Military Gear Resized Backpacks",
      "workshopId": "2873692310"
    },
    {
      "name": "MMG - Mightys Military Gear",
      "workshopId": "2663169692"
    },
    {
      "name": "Mortys Weapons",
      "workshopId": "2155726353"
    },
    {
      "name": "SNAFU Weapons",
      "workshopId": "2443122116"
    },
    {
      "name": "Ear-Plugs",
      "workshopId": "1819514788"
    },
    {
      "name": "Code Lock",
      "workshopId": "1646187754"
    },
    {
      "name": "Advanced Weapon Scopes",
      "workshopId": "2143128974"
    }
  ],

**Comment by onlinylee** [comment]
After many, many times of testing, it may be related to network fluctuations, and I can almost start successfully recently.

**Comment by onlinylee** [comment]
@mr-guard In addition, hello author, can I use the dayz-sever-manager program to record a server construction tutorial? And post in bilibili.com request authorization!

**Comment by mr-guard** [comment]
@onlinylee Of course!
I would be glad if you could upload it to youtube or vimeo as well.
If it is helpful and not too specific I will include it in the in the ReadMe if you are ok with it

**Comment by onlinylee** [comment]
My mother tongue is Mandarin, I hope you don't mind, I have no audience in YT, but I have uploaded and uploaded the subtitles for machine translation of the dialogue, maybe it can help understand.

https://youtu.be/1XXO7EYR3NY?si=ocwEcHF4Vk4SiIUf

**Comment by mr-guard** [comment]
Nice video and thanks for the effort!
The autotranslation could be a bit misleading sometimes so I wont add it to the README just yet (maybe yt will improve it down the road).

I will close this issue as resolved for now
