### ISSUE TITLE
Using DZSAModServer.exe causes  WARNING: Server possibly got stuck!

### ISSUE THREAD

**Issue by defib** [mr-guard/dayz-server-manager#75]
Once I switched to using DZSA to launch the server, I get  WARNING: Server possibly got stuck! quite often. Is there a way to hook in properly?

**Comment by mr-guard** [comment]
The warning usually occurs when the server either gets stuck or enters the economy idle mode.

You can either disable the idle mode or disable the warning by setting "disableStuckCheck" to true in the server manager json

**Comment by defib** [comment]
Good to know, but I don't believe that is the issue. To test I swapped `serverExe` back to `DayZServer_x64.exe`, had a player log in, and no message was thrown. 

However, once I swapped back to `"serverExe": "DZSALModServer.exe"`, the errors kept coming even when a player was logged in. I will enable `disableStuckCheck` for now. Let me know if I can help debug at all

**Comment by mr-guard** [comment]
Ahh ok

In this case the DZSALModServer probably launches the server as a subprocess.
The server manager only checks the main process which probably doesnt do anything and therefore "appears to be stuck" to the manager

**Comment by defib** [comment]
Attached is a screenshot of the server running using this config, in case it may help you. If there are any other logs you want, I can shoot it over.

<img width="1383" alt="image" src="https://github.com/mr-guard/dayz-server-manager/assets/779860/8f29404b-98aa-4441-a8e2-b6829ad6b8b4">

**Comment by mr-guard** [comment]
Since I cannot really track subprocesses I will close this as a "non issue" (since you can disable and ignore the warning in this case)
