### ISSUE TITLE
Using more than 1 mod in your config makes the dayz-server manager install process crash

### ISSUE THREAD

**Issue by dm5xx** [mr-guard/dayz-server-manager#81]
First i looked llike it was the same problem like the issue (#8) before, but its different!

- Using a complete installation of the servermanager from the scratch.
- my steam user has a valid dayz license 
- i am steamcmd logged in sucessfully. 
- dayzserver is downloaded verified and installed. all fine.
- testing: started always from scratch (no worshop-folder)

This is my modlist:
	"1559212036",
	"2545327648",
	"1564026768",
	"2430317812",
	"2793893086",
	"2792982069",
	"2572331007"

=> ERROR!
...
@2023-11-23T18:13:36.014Z | INFO | SteamCMD | Server Update Progress: verifying update: 94.76% - []
@2023-11-23T18:13:38.043Z | INFO | SteamCMD | Server Update Progress: committing: 0.00% - []
@2023-11-23T18:13:39.489Z | ERROR | SteamCMD | Mod 1559212036 was not found - []
@2023-11-23T18:13:48.536Z | INFO | SteamCMD | Downloading mod: 2572331007 - []
@2023-11-23T18:16:02.280Z | INFO | SteamCMD | Downloading mod: 2793893086 - []
@2023-11-23T18:16:17.191Z | INFO | SteamCMD | Downloading mod: 2792982069 - []
@2023-11-23T18:16:48.296Z | ERROR | SteamCMD | Failed to update mods: 2792982069,2545327648,1564026768,1559212036,2430317812
@2023-11-23T18:16:48.314Z | ERROR | Bootstrap | Setup failed: Updating Mods failed [
Error: Updating Mods failed
at ManagerController. (C:\snapshot\dayz-server-manager\dist\control\manager-controller.js:203:27)
at Generator.next ()
at fulfilled (C:\snapshot\dayz-server-manager\dist\control\manager-controller.js:14:58)
]

removing all mods => 
dayz-server-manager installation is working fine. dayz server is spawened.

using just for example 1559212036 =>
dayz-server-manager installation is working fine. dayz server is spawened incl. the mod.

adding another mod => 
dayz-server-manager installation process crashes. regardless which mod you add second.

So something internally is broken - no idea what. if you have just 1 mod to add, you are lucky... any idea?

**Comment by mr-guard** [comment]
We have multiple people on the discord and on my team who use the server manager with many mods.
So its not something thats gerally wrong with the manager

Could you set the log level to debug and check if there are any additional hints on whats wrong?
Please do not post the log on debug level here as it could include credentials. If you think I should still check them, join the discord and PM them to me

**Comment by dm5xx** [comment]
where is the discord, ill do that.

**Comment by mr-guard** [comment]
Use the "Chat" button/badge in the readme

**Comment by dm5xx** [comment]
I will leave this issue for the future,hihi... it was a layer8 problem... 2430317812 is not a valid workshop id... ok, it is, but it has nothing to do with needed content. dont ask my why its there. didn see it - was going nuts. so better check ur mod ids (hahaha, i did, but not if they are valid :P)
m.
