### ISSUE TITLE
Stop server mod updates

### ISSUE THREAD

**Issue by InnerSanctuary** [mr-guard/dayz-server-manager#83]
I have the following settings in server-manager.json

 "updateModsBeforeServerStart": false,
"updateServerBeforeServerStart": false,
 "updateServerOnStartup": false,

Which are all the settings i can find that stop mods from updating.  Today Expansion mod updates came out and nuked my server, it will no longer even start.  How come the above settings did not work.

**Comment by mr-guard** [comment]
there is also "updateModsOnStartup"

**Comment by InnerSanctuary** [comment]
crap i missed that, thanks!
