### ISSUE TITLE
Server Is Not Starting

### ISSUE THREAD

**Issue by seerweb** [mr-guard/dayz-server-manager#84]
There are errors when starting. I can't figure out what's missing.

<img width="867" alt="Снимок экрана 2023-12-05 011024" src="https://github.com/mr-guard/dayz-server-manager/assets/40312764/c13fcc47-90e5-4bbd-8eff-d92ad95f8854">

**Comment by MortanisNox** [comment]
The configuration file provided is a template, you have to remove template from the filename.

**Comment by seerweb** [comment]
> The configuration file provided is a template, you have to remove template from the filename.

Thanks! I've already figured it out.

**Comment by mr-guard** [comment]
I assume this is resolved
please create a new issue if there are any other errrors
