### ISSUE TITLE
NULL pointer to instance. Function: 'unregisterVehicle'

### ISSUE THREAD

**Issue by D4VOS** [mr-guard/dayz-server-manager#87]
I found such a crash log. There are many more and only the classes of vehicles change. 

```
NULL pointer to instance
Class:      'Sedan_02_Grey'
Entity id:3002702

Function: 'unregisterVehicle'
Stack trace:
DayZServerManager/Scripts/4_World/dayzservermanager\entities\dayzservermanagercontainer.c:20
DayZServerManager/Scripts/4_World/dayzservermanager\entities\carscript.c:10

Runtime mode
CLI params: config serverDZ.cfg port <PORT>profiles profiles mod @Code-Lock;@Mod-Options;@SchanaParty;@Server_Information_Panel;@Basic-Territories;@BuildEverywhere;@Basic-Map;@InvincibleFlag;@Autorun-Mod;@WornRepair;@KillFeed-Lanky;@Building-Fortifications;@VPPAdminTools;@StackMoreItems;@CF;@SchanaModGlobalChat;@NoVehicleDamage;@ProjectHope-Survivor-Backpack;@Airdrop-Upgraded;@Ear-Plugs;@BasicSpawnSelect;@Unlimited-Stamina;@KOTH servermod @DayZServerManager;@CF adminlog  dologs  freezecheck  scrAllowFileWrite  scriptDebug  
```

**Comment by BastyJuice** [comment]
I had such errors too, it's not directly the manager's fault. I tried to specify the real path in profile but only in profile that helped me for me my Patch is C:\\Gameserver\\DayZ\\Server\\profiles and yes Double \\ is right

**Comment by D4VOS** [comment]
> I had such errors too, it's not directly the manager's fault. I tried to specify the real path in profile but only in profile that helped me for me my Path is C:\Gameserver\DayZ\Server\profiles and yes Double \ is right

Do I understand correctly? Did you set the absolute path to profiles in server-manager.json?

**Comment by BastyJuice** [comment]
Yes Important is that you do it with \\ `C:\\Gameserver\\DayZ\\Server\\profile`

**Comment by D4VOS** [comment]
Unfortunately, I still have this error. 
`"profilesPath": "C:\\Users\\dayz\\Desktop\\dayz-server-manager\\dayz-server\\profiles",`

**Comment by mr-guard** [comment]
Its something in the watcher mod. I cannot reproduce it though.

I will add a potential fix in the next update

**Comment by mr-guard** [comment]
Could you test it again with the latest version?

**Comment by D4VOS** [comment]
Seems ok :)

**Comment by Setman590** [comment]
It seems to come up when I am running Expansion.

**Comment by mr-guard** [comment]
Can you verify this in the latest version?

**Comment by Setman590** [comment]
Looks like it went away with the new version.
Thanks

**Comment by mr-guard** [comment]
Great, gonna close this as resolved then
