### ISSUE TITLE
Discord Bot with more then one role and channel

### ISSUE THREAD

**Issue by St0n3waLL82** [mr-guard/dayz-server-manager#89]
Hi team,

i've found an issue with the configurarion of more then one discord channel with different roles.

This is my configurarion in web interface:
![image](https://github.com/mr-guard/dayz-server-manager/assets/155621815/072cf495-b88b-4aec-8d0c-2ac450f9ea35)

Inside the server-manager.json it looks like this:

 {
      "channel": "commands",
      "mode": [
        "admin"
      ]
    },
    {
      "channel": "log",
      "mode": [
        "rcon"
      ]
    },

When i try to execute an command from my commands channel im getting the message:
This command is not allowed in this channel.

Changing the settings in server-manager.json to the following solves my problem and the commands are working (removing [ ] from mode selection):

 {
      "channel": "commands",
      "mode": "admin"
    },
    {
      "channel": "log",
      "mode": "rcon"
    },

But: Everytime when i save any setting in WebGui the discord settings will be reverted to the not working one and i need to remove the [ and ] again.

Best regards,

St0n3waLL

**Comment by mr-guard** [comment]
Good catch and sorry for the inconvenience

will be fixed in the next update

**Comment by St0n3waLL82** [comment]
Awesome! And thanks for your great Work!
