### ISSUE TITLE
cfggameplay.json will be overwritten at restart

### ISSUE THREAD

**Issue by bruunooh** [mr-guard/dayz-server-manager#92]
I have found that the cfggameplay.json is overwritten every time the manager is restarted. Stamina Settings and Custom Loadout are therefore not usable. Do you have a fix for this or have I overlooked a setting?

**Comment by mr-guard** [comment]
Disable validate server after update
The steam verification is reverting the file to the intital state

Other than that you can create a beforeStart hook that copies all custom files from somewhere else

**Comment by Villhahallon** [comment]
Renaming the mission folder helped me with that problem also, As described in the guide. 
Renaming the "dayzOffline.chernarusplus" to "dayz.chernarusplus" stopped overwriting my custom files.

Just an alternative way that seems to work 🤷
