### ISSUE TITLE
Server Installation Failed

### ISSUE THREAD

**Issue by Oystercracker1** [mr-guard/dayz-server-manager#93]
@2024-01-13T15:36:03.478Z | INFO      | SteamCMD     | Progress: ---- - Extracting package...
@2024-01-13T15:36:05.845Z | INFO      | SteamCMD     | Progress: ---- - Installing update...
@2024-01-13T15:36:06.783Z | INFO      | SteamCMD     | Progress: ---- - Cleaning up...
@2024-01-13T15:36:06.814Z | INFO      | SteamCMD     | Progress: ---- - Update complete, launching Steamcmd...
@2024-01-13T15:36:06.999Z | INFO      | SteamCMD     | Progress:   0% - Checking for available updates...
@2024-01-13T15:36:07.757Z | INFO      | SteamCMD     | Progress: ---- - Verifying installation...
@2024-01-13T15:36:18.161Z | INFO      | SteamCMD     | Server Update Progress: reconfiguring: 0.00%
@2024-01-13T15:36:20.022Z | INFO      | SteamCMD     | Server Update Progress: reconfiguring: 0.00%
@2024-01-13T15:36:20.576Z | ERROR     | SteamCMD     | SteamCMD "+force_install_dir C:\Users\Jack Oosterhuis\Downloads\server-manager-windows\DayZServer +login Oystercracker1 ****** +app_update 223350 validate +quit" failed [
  {
    status: 8,
    stdout: "Redirecting stderr to 'C:\\Users\\Jack Oosterhuis\\Downloads\\server-manager-windows\n" +
      "\\SteamCMD\\logs\\stderr.txt'\n" +
      "Logging directory: 'C:\\Users\\Jack Oosterhuis\\Downloads\\server-manager-windows\\St\n" +
      "eamCMD/logs'\n" +
      '[  0%] Checking for available updates...[----] Verifying installation...Steam Console Client (c) Valve Corporation - version 1705108307\n' +
      "-- type 'quit' to exit --\n" +
      'Loading Steam API...OK\n' +
      "Logging in user 'Oystercracker1' to Steam Public...OK\n" +
      'Waiting for client config...OK\n' +
      "Waiting for user info...OKUpdate state (0x3) reconfiguring, progress: 0.00 (0 / 0)Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)Error! App '223350' state is 0x202 after update job.",
    stderr: ''
  }
]
@2024-01-13T15:36:20.579Z | WARN      | Discord      | Queueing message because client did not start or is not yet ready [ false ]
@2024-01-13T15:36:20.580Z | ERROR     | SteamCMD     | Failed to update server
@2024-01-13T15:36:20.581Z | ERROR     | Bootstrap    | Setup failed: Server installation failed [
  Error: Server installation failed
      at ManagerController.<anonymous> (C:\snapshot\dayz-server-manager\dist\control\manager-controller.js:195:27)
      at Generator.next (<anonymous>)
      at fulfilled (C:\snapshot\dayz-server-manager\dist\control\manager-controller.js:14:58)
]
Press any key to continue . . .

The only information entered into config json file is my steam info.

Not sure how to proceed!

**Comment by mr-guard** [comment]
Errorcode 0x202 from steamcmd means "Out of disk space"

Could you check if there is enough space left on your disk?

**Comment by Oystercracker1** [comment]
Oh geez thank you - disk was near full
