### ISSUE TITLE
No Issue Hooks question

### ISSUE THREAD

**Issue by Setman590** [mr-guard/dayz-server-manager#99]
Hi Guys,

I I want to use BEC to restart my sever, but can't get this to work,

    "hooks": [
	       "type": "beforeStart",
               "program": "bec.exe",
               "params": ["/i", "server-manager-0\0\BEC\StartBEC.bat"]
	],
Did I miss something?
Thanks

**Comment by mr-guard** [comment]
If you want to run a batch file, your "program" needs to be the batchfile itself or "cmd.exe"

Notes:
"\" is a escape character in JSON, so you to replace it with double \ ("\\").
You were missing some brackets which denote objects

The path has to be relative to where the servermanager.exe is located
Probably "server-manager-0" is the folder where the  servermanager.exe is located, so it needs to be removed
If you use the batch as program, the backslashes can be replaced by normal slashes

This one should work
```json
"hooks": [
  {
       "type": "beforeStart",
       "program": "./0/BEC/StartBEC.bat"
  }
],
```

**Comment by Setman590** [comment]
I must still be missing something this error keeps coming up.

 ERROR     | Hooks        | beforeStart Hook (./0/BEC/StartBEC.bat ) failed - [{"status":1,"stdout":"","stderr":"'.' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"}]

**Comment by Setman590** [comment]
Works great thanks

**Comment by Setman590** [comment]
Does  the afterStart work? I am using

    "hooks": [
	    {
            "type": "afterStart",
            "program": "./chernarusplus/bec/Startbec.bat"
		}
	],
